name: hsluvsample
description: HSLuv sample.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  bloc: ^6.1.0
  effective_dart: ^1.3.0
  flutter:
    sdk: flutter
  google_fonts: ^1.1.1
  hsluv:
    path: ../
  flutter_bloc: ^6.1.1
  equatable: ^1.2.5
  rxdart: ^0.24.1
  flutter_feather_icons: ^1.0.3
  infinite_listview: ^1.0.1+1
  url_launcher: ^5.4.2
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  path_provider: ^1.6.24

dev_dependencies:
  build_runner: ^1.10.4
  flutter_launcher_icons: ^0.8.1
  hive_generator: ^0.8.2
  flutter_test:
    sdk: flutter

flutter_icons:
  # unfortunately, this only works without bugs for iOS.
  # you need to open Android Studio and generate asset if you want a decent Android icon.
  image_path_android: "assets/full icon.png"
  image_path_ios: "assets/full icon.png"
  android: false
  ios: true
  adaptive_icon_background: "assets/sample_bg.png" # Android 8+
  adaptive_icon_foreground: "assets/sample_fg.png" # Android 8+


flutter:
  uses-material-design: true

  fonts:
    - family: B612Mono
      fonts:
        - asset: fonts/B612Mono-Regular.ttf
          weight: 400
        - asset: fonts/B612Mono-Bold.ttf
          weight: 700
  assets:
    - assets/colornames.json
