name: hsluv
description: Dart port of HSLuv, a human-friendly alternative to HSL based on human experiments.
homepage: https://github.com/bernaferrari/hsluv-dart
version: 1.1.3

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
