name: hsluv
description: Dart port of HSluv.
author: Bernardo Ferrari <bernaferrari2@gmail.com>
homepage: https://github.com/bernaferrari/hsluv
version: 1.0.0

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
