name: hsluv
description: Dart port of HSLuv, a human-friendly alternative to HSL based on human experiments.
homepage: https://github.com/bernaferrari/hsluv-dart
version: 1.0.6

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
